spring.application.name=example


spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=hemsagar
spring.datasource.password=MotherSas1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/
server.port=8080